// <auto-generated />
namespace AcTimer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update_CategoryModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_CategoryModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201805271646192_Update_CategoryModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
